# Generated by Django 5.1.1 on 2024-09-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('product_expiry_date', models.DateField()),
                ('product_manufacturing_date', models.DateField()),
                ('product_HSN_no', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
            ],
        ),
    ]
